"use client";
import { useEffect, useRef, useState } from "react";
import type { MouseEvent, PointerEvent, WheelEvent } from "react";
const GRID_COLS=200, GRID_ROWS=145, BLOCK_SIZE=10, MAP_WIDTH=2000, MAP_HEIGHT=1450;
type Cat="SOLIDARITY"|"PREMIUM"|"GRAND_CENTER";
type ApiMapBlock={id:string;gridX:number;gridY:number;category:Cat;status:string;available:boolean;priceCents:number;owner:{name:string;publicName:string|null;totalApprovedCents:number}|null;placement:{id:string;kind:string;status:string;title:string|null;description:string|null;imageUrl:string|null;redirectUrl:string|null;linkDisabled:boolean;displayName:string|null;textLabel:string|null;fillColor:string|null;placeholderReason:string|null}|null};
type Selected=null|{type:"grand-center"}|{type:"sold";block:ApiMapBlock}|{type:"solidarity"}|{type:"premium"};
function getBlockType(x:number,y:number):Cat{if(x>=99&&x<=100&&y>=70&&y<=74)return"GRAND_CENTER";if(y<25||y>=120)return"SOLIDARITY";return"PREMIUM"}
function money(cents:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100)}
function key(x:number,y:number){return `${x}:${y}`}
function displayName(b:ApiMapBlock){return b.placement?.displayName||b.placement?.textLabel||b.owner?.publicName||b.owner?.name||"Apoiador"}
export default function PixelMap(){
 const canvasRef=useRef<HTMLCanvasElement|null>(null), wrapperRef=useRef<HTMLDivElement|null>(null), dragging=useRef(false), last=useRef({x:0,y:0});
 const [camera,setCamera]=useState({x:0,y:0,scale:1}),[blocks,setBlocks]=useState<ApiMapBlock[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Selected>(null);
 useEffect(()=>{const w=wrapperRef.current;if(!w)return;const r=w.getBoundingClientRect();setCamera({x:r.width/2-Math.random()*MAP_WIDTH,y:r.height/2-Math.random()*MAP_HEIGHT,scale:1})},[]);
 useEffect(()=>{let alive=true;(async()=>{try{setLoading(true);const res=await fetch("/api/map/blocks",{cache:"no-store"});const data=await res.json();if(alive&&data.ok)setBlocks(data.blocks)}catch(e){console.error(e)}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 useEffect(()=>{draw()},[camera,blocks]);
 function getAt(x:number,y:number){return blocks.find(b=>b.gridX===x&&b.gridY===y)}
 function draw(){
  const c=canvasRef.current,w=wrapperRef.current;if(!c||!w)return;const r=w.getBoundingClientRect(),dpr=window.devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;c.style.width=`${r.width}px`;c.style.height=`${r.height}px`;const ctx=c.getContext("2d");if(!ctx)return;
  const sold=new Map(blocks.map(b=>[key(b.gridX,b.gridY),b]));ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle="#f8fafc";ctx.fillRect(0,0,r.width,r.height);ctx.save();ctx.translate(camera.x,camera.y);ctx.scale(camera.scale,camera.scale);
  for(let y=0;y<GRID_ROWS;y++)for(let x=0;x<GRID_COLS;x++){const type=getBlockType(x,y),b=sold.get(key(x,y)),px=x*BLOCK_SIZE,py=y*BLOCK_SIZE;ctx.fillStyle=b?(b.category==="PREMIUM"?"#0f172a":b.placement?.fillColor||"#16a34a"):type==="GRAND_CENTER"?"#facc15":type==="SOLIDARITY"?"#bbf7d0":"#e2e8f0";ctx.fillRect(px,py,BLOCK_SIZE,BLOCK_SIZE);ctx.strokeStyle="rgba(15,23,42,.12)";ctx.lineWidth=.3;ctx.strokeRect(px,py,BLOCK_SIZE,BLOCK_SIZE);if(b&&camera.scale>=2){ctx.fillStyle="#fff";ctx.font="7px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("✓",px+5,py+5)}}
  ctx.fillStyle="#78350f";ctx.font="18px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("🔒",1000,725);ctx.restore()
 }
 function grid(clientX:number,clientY:number){const w=wrapperRef.current;if(!w)return null;const r=w.getBoundingClientRect();const wx=(clientX-r.left-camera.x)/camera.scale,wy=(clientY-r.top-camera.y)/camera.scale;const x=Math.floor(wx/BLOCK_SIZE),y=Math.floor(wy/BLOCK_SIZE);if(x<0||x>=GRID_COLS||y<0||y>=GRID_ROWS)return null;return{x,y,type:getBlockType(x,y)}}
 function goSold(){const w=wrapperRef.current;if(!w||!blocks.length){alert("Ainda não há blocos vendidos.");return}const r=w.getBoundingClientRect(),b=blocks[0],s=4;setCamera({x:r.width/2-(b.gridX*10+5)*s,y:r.height/2-(b.gridY*10+5)*s,scale:s})}
 function goCenter(){const w=wrapperRef.current;if(!w)return;const r=w.getBoundingClientRect(),s=3;setCamera({x:r.width/2-1000*s,y:r.height/2-725*s,scale:s})}
 function down(e:PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);dragging.current=true;last.current={x:e.clientX,y:e.clientY}}
 function move(e:PointerEvent<HTMLDivElement>){if(!dragging.current)return;const dx=e.clientX-last.current.x,dy=e.clientY-last.current.y;last.current={x:e.clientX,y:e.clientY};setCamera(c=>({...c,x:c.x+dx,y:c.y+dy}))}
 function up(){dragging.current=false}
 function click(e:MouseEvent<HTMLDivElement>){const p=grid(e.clientX,e.clientY);if(!p)return;const b=getAt(p.x,p.y);if(b){setSelected({type:"sold",block:b});return}if(p.x>=98&&p.x<=101&&p.y>=69&&p.y<=75){setSelected({type:"grand-center"});return}setSelected({type:p.type==="SOLIDARITY"?"solidarity":"premium"})}
 function wheel(e:WheelEvent<HTMLDivElement>){e.preventDefault();setCamera(c=>({...c,scale:Math.min(5,Math.max(.4,e.deltaY>0?c.scale*.9:c.scale*1.1))}))}
 return <div ref={wrapperRef} className="relative h-full w-full cursor-grab touch-none select-none overflow-hidden bg-slate-100 active:cursor-grabbing" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onClick={click} onWheel={wheel}>
  <canvas ref={canvasRef} className="block h-full w-full"/>
  <div className="absolute left-4 right-4 top-4 z-40 flex gap-2"><button onClick={e=>{e.stopPropagation();goSold()}} className="flex-1 rounded-full bg-green-600 px-4 py-3 text-xs font-black text-white shadow-lg">{loading?"Carregando...":`Vendidos ${blocks.length}`}</button><button onClick={e=>{e.stopPropagation();goCenter()}} className="flex-1 rounded-full bg-yellow-400 px-4 py-3 text-xs font-black text-yellow-950 shadow-lg">Centro 🔒</button></div>
  {selected?.type==="grand-center"&&<div className="fixed inset-0 z-[999] flex items-center justify-center bg-slate-950/50 p-6" onClick={()=>setSelected(null)}><div className="w-full max-w-sm rounded-3xl bg-white p-6 text-center shadow-2xl" onClick={e=>e.stopPropagation()}><div className="text-5xl">🔒</div><h2 className="mt-3 text-2xl font-black">Área bloqueada</h2><p className="mt-2 text-sm text-slate-600">Reservado para algo grandioso. Em breve.</p><button onClick={()=>setSelected(null)} className="mt-6 w-full rounded-2xl bg-slate-950 py-4 text-sm font-extrabold text-white">Entendi</button></div></div>}
  {selected?.type==="sold"&&<div className="fixed inset-x-0 bottom-0 z-[999] rounded-t-3xl bg-white p-5 shadow-2xl"><div className="flex h-32 items-center justify-center rounded-3xl bg-green-600 text-white"><div className="text-center"><div className="text-4xl">{selected.block.category==="PREMIUM"?"🔥":"💚"}</div><p className="mt-2 text-sm font-black">Bloco vendido</p></div></div><p className="mt-4 text-xs font-black uppercase text-slate-500">{selected.block.category==="PREMIUM"?"Área Premium":"Mosaico Solidário"}</p><h2 className="mt-1 text-xl font-black">{displayName(selected.block)}</h2><p className="mt-2 text-sm text-slate-600">{selected.block.placement?.description||"Esse apoiador já faz parte do Milhão Solidário."}</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-slate-50 p-3 text-center"><p className="text-[10px] font-black uppercase text-slate-500">Posição</p><p className="text-sm font-black">x{selected.block.gridX} / y{selected.block.gridY}</p></div><div className="rounded-2xl bg-green-50 p-3 text-center"><p className="text-[10px] font-black uppercase text-green-700">Valor</p><p className="text-sm font-black text-green-800">{money(selected.block.priceCents)}</p></div></div><button onClick={()=>setSelected(null)} className="mt-3 w-full rounded-2xl bg-slate-950 py-4 text-sm font-extrabold text-white">Fechar</button></div>}
  {selected?.type==="solidarity"&&<Sheet title="Mosaico Solidário" icon="💚" text="Bloco rápido de R$ 10,00. O apoiador informa apenas o nome completo." href="/checkout" button="Comprar por R$ 10,00" close={()=>setSelected(null)} color="bg-green-500"/>}
  {selected?.type==="premium"&&<Sheet title="Área Premium" icon="🔥" text="Bloco premium de R$ 100,00. Permite imagem, título, descrição e link." href="/checkout" button="Comprar bloco Premium" close={()=>setSelected(null)} color="bg-orange-500"/>}
 </div>
}
function Sheet({title,icon,text,href,button,close,color}:{title:string;icon:string;text:string;href:string;button:string;close:()=>void;color:string}){return <div className="fixed inset-x-0 bottom-0 z-[999] rounded-t-3xl bg-white p-5 shadow-2xl"><div className={`mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full ${color} text-3xl text-white shadow-lg`}>{icon}</div><h2 className="text-center text-xl font-black">{title}</h2><p className="mt-2 text-center text-sm text-slate-600">{text}</p><a href={href} className={`mt-5 block w-full rounded-2xl ${color} py-4 text-center text-sm font-extrabold text-white shadow-lg`}>{button}</a><button onClick={close} className="mt-3 w-full rounded-2xl bg-slate-950 py-4 text-sm font-extrabold text-white">Fechar</button></div>}
